### ISSUE TITLE
Add autocomplete to sign in form

### ISSUE THREAD

**Issue by jcla490** [washington-dnr-fire/project-space-crab#16]
https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands

I'm not sure at the moment how to get at the form elements to add these fields. Perhaps with jquery after load...

**Comment by kirk5davis** [comment]
This is browser based.  Already works, additionally you can save your password and it will auto-log-you-in. See photo: 
![IMG_20190623_091701](https://user-images.githubusercontent.com/12001202/59979092-ee2c6d00-9597-11e9-9ae2-664f79b5cac0.jpg)
