### ISSUE TITLE
Fix IFPL and Fire Danger loading issues

### ISSUE THREAD

**Issue by jcla490** [washington-dnr-fire/project-space-crab#27]

**Comment by kirk5davis** [comment]
switched IFPL and Fire Danger Layers to use dynamicMapLayer - now rendered using png-tiles and not geojson features.  Speed is improved, layer loads 100% when turned on. Addressed with: 6f2e335084831ee8ea27e626c4abd020930b70e6

**Comment by kirk5davis** [comment]
Also, Liza Weeks was asking if I could add the IFPL zone labels because someone asked her to zoom to a specific zone and she couldn't tell what was what.  The labels are included in the map service.  Two for one fix.
